config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
  end

  resources :chats, only: [:index, :create]

  get "/search" => "searches#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  is_impressionable

  belongs_to :user
  has_many :favorites
  has_many :book_comments
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def favorite_count
    from  = Time.current.at_beginning_of_day
    to    = (from + 6.day).at_end_of_day
    favorites.where(created_at: from...to).length
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :room
  belongs_to :user

  validates :content, length: { maximum: 140 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :chats
  has_many :room_users
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :favorites
  has_many :book_comments
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :relationshiped, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :is_followed, through: :relationshiped, source: :follower
  has_many :room_users, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  # validates :introduction, presence: true

  def is_following?(user)
    followings.include?(user)
  end

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  impressionist :actions => [:show]

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @book_comments = @book.book_comments
    @new_comment = BookComment.new
    impressionist(@book, nil, unique: [:session_hash.to_s])
  end

  def index
    @books = Book.all.sort { |a, b|
      b.favorite_count <=> a.favorite_count
    }
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    # bookの所有者ではないユーザーがURLに直接アクセスした場合にbook一覧にリダイレクトする
    if @book.user != current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destoy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
    @user = User.find(params[:id])
    rooms = current_user.room_users.pluck(:room_id)
    user_rooms = RoomUser.find_by(user_id: @user.id, room_id: rooms)

    if user_rooms.nil?
     @room = Room.new
     @room.save
     RoomUser.create(user_id: @user.id, room_id: @room.id)
     RoomUser.create(user_id: current_user.id, room_id: @room.id)
    else
     @room = user_rooms.room
    end

    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end

  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
  end

  private
  def chat_params
    params.require(:chat).permit(:content, :room_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    if params[:obj] == "Book"
      if params[:search_method] == "all"
        @books = Book.where(title: params[:content])
      elsif params[:search_method] == "after"
        @books = Book.where('title like ?', "%#{params[:content]}")
      elsif params[:search_method] == "before"
        @books = Book.where('title like ?', "#{params[:content]}%")
      end
      @book = Book.new
      render template: "books/index"
    end

    if params[:obj] == "User"
      if params[:search_method] == "all"
        @users = User.where(name: params[:content])
      elsif params[:search_method] == "after"
        @users = User.where('name like ?', "%#{params[:content]}")
      elsif params[:search_method] == "before"
        @users = User.where('name like ?', "#{params[:content]}%")
      end
      @book = Book.new
      render "users/index"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.where.not(id: current_user.id)
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <%= form_with url:search_path, method: :get ,local:true do |f| %>
    <%= f.text_field :content  %>
    <%= f.select :obj, [["ユーザー", "User"], ["投稿", "Book"]], include_blank: "選択して下さい" %>
    <%= f.select :search_method, [["前方一致", "before"], ["後方一致", "after"], ["完全一致", "all"]], include_blank: "選択して下さい" %>
    <%= f.submit "検索" %>
  <% end %>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td id="favorite_buttons_<%= book.id %>">
          <%= render "favorites/favorite", book: book %>
        </td>
        <td>コメント数：<%= book.book_comments.count %></td>
        <td>閲覧数：<%= book.impressionist_count(:filter=>:session_hash) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'layouts/errors', obj: @book %>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>

      <%= render 'books/index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @new_book %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td id="favorite_buttons_<%= @book.id %>"><%= render "favorites/favorite", book: @book %></td>
          <td>閲覧数：<%= @book.impressionist_count(:filter=>:session_hash) %></td>
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
        </tr>
      </table>
      <div>
        <p>コメント件数：<%= @book_comments.count %></p>
        <div class='comments'>
          <% @book_comments.each do |comment| %>
            <div>
              <%= comment.user.name %>
              <%= comment.created_at.strftime('%Y/%m/%d') %><%= comment.comment %>
              <% if comment.user == current_user %>
                <%= link_to "削除", book_book_comment_path(comment.book_id, comment.id), method: :delete %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
      <div>
        <%= form_with model: [@book, @new_comment], local: false, id: 'comment_form' do |f| %>
          <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
          <%= f.submit "送信する", {id: "comment_submit" } %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/chats/create.js.erb
$('.chats').append("<p style='text-align: right;'><%= @chat.content %></p>");

$('input[type=text]').val("")

app/views/chats/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-10">
      <h2>ダイレクトメッセージ</h2>

      <table class="table">
        <thead>
          <tr>
            <th style="text-align: left; font-size: 20px;"><%= @user.name %></th>
            <th style="text-align: right; font-size: 20px;"><%= current_user.name %></th>
          </tr>
        </thead>
      </table>

      <div class='chats'>
        <% @chats.each do |chat| %>
          <% if chat.user_id != current_user.id %>
            <p style="text-align: left;"><%= chat.content %></p>
          <% else %>
            <p style="text-align: right;"><%= chat.content %></p>
          <% end %>
        <% end %>
      </div>

      <div style="margin-top: 30px">
        <%= form_with model: @chat, local: false do |f| %>
          <%= f.text_field :content %>
          <%= f.hidden_field :room_id %>
          <%= f.submit "SEND", class:"btn btn-sm btn-success chat-btn" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_index.html.erb
<table class='table'>
  <%= form_with url:search_path, method: :get ,local:true do |f| %>
    <%= f.text_field :content  %>
    <%= f.select :obj, [["ユーザー", "User"], ["投稿", "Book"]], include_blank: "選択して下さい" %>
    <%= f.select :search_method, [["前方一致", "before"], ["後方一致", "after"], ["完全一致", "all"]], include_blank: "選択して下さい" %>
    <%= f.submit "検索" %>
  <% end %>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
        <% if current_user.is_following?(user) %>
          <td><%= link_to "フォローを解除する", user_relationships_path(user.id), method: :delete %></td>
          <% if user.is_following?(current_user) %>
            <td><%= link_to "DMする", chats_path({id: user.id}) %></td>
          <% end %>
        <% else %>
          <td><%= link_to "フォローする", user_relationships_path(user.id), method: :post %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= user.followings.count %></th>
  </tr>
    <tr>
    <th>followers</th>
    <th><%= user.is_followed.count %></th>
  </tr>
</table>

<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-md-7">
      <h2 >Users</h2>
      <%= render 'users/index', users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>